Add username validation feature
octoposprime/op-be-user pull request #16
Opened 2024-02-29 16:11 UTC by Smnrgcl

This pull request adds the CheckUserNameSpecialCharacters function to the Service struct to validate whether a username conforms to certain rules. During username validation, it checks whether the name contains only letters, numbers, hyphens, or underscores. This change ensures that the username is in the correct format during user registration. Additionally, this pull request enhances code extensibility by adding a new function to the Service struct.

2024-03-02 04:01 UTC, Sddilora commented
Enhancements are needed in error handling as the message 'Username is not valid' lacks specificity, potentially confusing users about the rules and necessary corrections.

2024-03-03 20:28 UTC, Sddilora commented
There are the definitions of the Error variables in, [domain package](https://github.com/octoposprime/op-be-user/blob/phase1/internal/domain/model/object/error.go). 

```go
        ErrorUserUsernameIsEmpty                            error = errors.New(smodel.ErrBase + smodel.ErrSep + ErrUser + smodel.ErrSep + ErrUserName + smodel.ErrSep + ErrEmpty)
	ErrorUserUsernameIsExists                           error = errors.New(smodel.ErrBase + smodel.ErrSep + ErrUser + smodel.ErrSep + ErrUserName + smodel.ErrSep + ErrAlreadyExists)
	ErrorUserUsernameIsTooShort                         error = errors.New(smodel.ErrBase + smodel.ErrSep + ErrUser + smodel.ErrSep + ErrUserName + smodel.ErrSep + ErrTooShort)
	ErrorUserUsernameIsTooLong                          error = errors.New(smodel.ErrBase + smodel.ErrSep + ErrUser + smodel.ErrSep + ErrUserName + smodel.ErrSep + ErrTooLong)
	ErrorUserUsernameIsNotValid                         error = errors.New(smodel.ErrBase + smodel.ErrSep + ErrUser + smodel.ErrSep + ErrUserName + smodel.ErrSep + ErrNotValid)
```
"Username cannot contain special characters" needs to be implemented in this way too. You can find the smdol.Errbase or other declarations in [model package of the shared library](https://github.com/octoposprime/op-be-shared/blob/phase1/pkg/model/error.go)

2024-03-03 20:33 UTC, Sddilora requested changes
Error handling methods should adhere to the project structure and be enhanced.

2024-03-04 12:36 UTC, husamettinarabaci requested changes
We have struct-based error types. Please keep our generic mo.Error*** styles. You have to add all new errors in model/object/error.go.

Note: in the Golang; any error message shouldn't start with a capital character.

2024-03-10 02:50 UTC, husamettinarabaci commented on internal/domain/service/service_test.go
> +ppackage domain
Please check this

2024-03-10 02:52 UTC, husamettinarabaci requested changes
Please caution this message;
https://github.com/octoposprime/op-be-user/pull/16#issuecomment-1975302539

2024-03-11 20:04 UTC, husamettinarabaci commented
Please remove;

var (
    ErrorUserUsernameIsEmpty            = errors.New("username is empty")
    ErrorUserUsernameIsTooShort         = errors.New("username is too short")
    ErrorUserUsernameIsTooLong          = errors.New("username is too long")
    ErrorUserUsernameContainsSpace      = errors.New("username contains space")
    ErrorUserUsernameContainsSpecialChars = errors.New("username contains special characters")
    ErrorUserUsernameContainsInvalidChars = errors.New("username contains invalid characters")
)

2024-03-15 13:49 UTC, Sddilora commented
![image](https://github.com/octoposprime/op-be-user/assets/122971619/df1f0c0f-1a5b-4408-af45-ac88bab1465c)
As in Godev's example, the name of the test suite should be the same as the name of the source package (the name of the package containing the function under test).

Also, such things should not be changed :)

2024-03-15 13:57 UTC, Sddilora commented on internal/domain/service/service_test.go
> -package domain
This part should be remained as "domain".

2024-03-15 13:57 UTC, Sddilora commented on internal/domain/service/service_test.go
> +package domain_test
This part should be remained as "domain".

2024-03-15 14:20 UTC, Sddilora commented on internal/domain/model/object/error.go
> +	ErrorUserUsernameContainsSpecialChars               error = errors.New(smodel.ErrBase + smodel.ErrSep + ErrUser + smodel.ErrSep + ErrUserName + smodel.ErrSep + ErrorUserUsernameContainsSpecialChars
initialization cycle: ErrorUserUsernameContainsSpecialChars refers to itselfcompiler[InvalidInitCycle](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#InvalidInitCycle)

2024-03-15 14:25 UTC, Sddilora commented on internal/domain/service/service.go
> +        return mo.ErrorUserUsernameContainsSpace
this is not present in mo

2024-03-15 14:26 UTC, Sddilora commented on internal/domain/model/object/error.go
> +	ErrorUserUsernameContainsInValidChars               error = errors.New(smodel.ErrBase + smodel.ErrSep + ErrUser + smodel.ErrSep + ErrUserName + smodel.ErrSep + ErrContainsInvalidChars)
typo causes error

2024-03-23 01:05 UTC, Sddilora commented
Let's start fresh with a new branch and close this pull request, as the current branch and PR are causing some confusion.

2024-03-23 01:05 UTC, closed without merging