Remove Authentication Layers from User Service
octoposprime/op-be-user pull request #62
Opened 2024-05-07 14:16 UTC by Smnrgcl

Close #57 
The 'authentication.go and authentication_test.go' file has been deleted.

2024-05-07 14:36 UTC, Feyzanrs commented
A few more files need to be deleted from the internal layer of the User Service. Could you check on them?

2024-05-07 14:46 UTC, Sddilora requested changes
Please delete any other files mentioned in the video as well.

2024-05-10 12:29 UTC, Sddilora approved these changes

2024-05-10 12:55 UTC, Maraza25 approved these changes

2024-05-10 12:55 UTC, merged