Edited userwithpassword.go file
octoposprime/op-be-user pull request #93
Opened 2024-06-02 12:46 UTC by Smnrgcl

Closes #80
 

The UserPassword struct has been updated to store the proto field as type pb.UserPassword. 
Additionally, the String method now hides the password, and the ToEntity method returns an entity of type me.UserPassword.

Similarly, the UserWithPassword struct stores the proto field as type pb.UserWithPassword. 
The NewUserWithPasswordFromEntity function constructs a UserWithPassword structure using entity representation. 
The ToEntity method returns both me.User and me.UserPassword entities.

A new function NewEmptyUserWithPassword has been added to the UserWithPassword struct, which generates an empty instance of UserWithPassword.

2024-06-04 10:54 UTC, ebrarkesici approved these changes, later dismissed

2024-06-05 14:29 UTC, Feyzanrs requested changes
This code needs to be added to a newly created file named 'userwithpassword.go' in our project. Currently, it appears to have been added to the existing 'userpassword.go' file. Could you please make the necessary changes and resubmit?

2024-06-05 17:05 UTC, Feyzanrs approved these changes

2024-06-05 22:15 UTC, ebrarkesici approved these changes

2024-06-06 17:23 UTC, merged